import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Box, Typography} from '@mui/material'
import {PortfolioAppBar} from '../components/portfolio-app-bar'

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Yuta Yamamori Portfolio</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/sunny.jpg"/>
      </Head>
      <Image src='/sunny.jpg' layout='fill' priority={true}/>
      <PortfolioAppBar pageTitle='Welcome'/>
      <Typography variant='h1'>
        Welcome!
      </Typography>
    </Box>
  )
}

export default Home
