import type {NextPage} from 'next'
import Head from 'next/head'
import {Box, Typography} from '@mui/material';
import {PortfolioAppBar} from '../components/portfolio-app-bar';

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Yuta Yamamori Portfolio</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <PortfolioAppBar pageTitle="はじめに" />
      <Typography variant='h1'>
        Welcome!
      </Typography>
    </Box>
  )
}

export default Home
